#!/bin/sh

###########################################################################
###
###  Copyright (c) 2007, Tsujii Laboratory, The University of Tokyo.
###  All rights reserved.
###
###  Name: run-enju
###  shell script to run enju
###
###########################################################################

BASE_DIR=`dirname $0`

# find the absolute path to this script
echo $BASE_DIR | grep -q '^/' 2> /dev/null > /dev/null
if [ $? != 0 ]; then
  BASE_DIR=`pwd`/$BASE_DIR
fi

# set environment variables
if [ -z "$ENJU_PREFIX" ]; then
  export ENJU_PREFIX=$BASE_DIR
fi

if [ -z "$ENJU_DIR" ]; then
  export ENJU_DIR=$BASE_DIR/lib/enju
fi

if [ -z "$LILFES_PATH" ]; then
  export LILFES_PATH=$BASE_DIR/share/liblilfes
else
  export LILFES_PATH=$BASE_DIR/share/liblilfes:$LILFES_PATH
fi

if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH=$BASE_DIR/lib
else
  export LD_LIBRARY_PATH=$BASE_DIR/lib:$LD_LIBRARY_PATH
fi

if [ "$ENJU_TAGGER" != "" ];
then
    DEFAULT_ENJU_TAGGER_OPT="-t $ENJU_TAGGER"
fi

if [ "$ENJU_MORPH" != "" ];
then
    DEFAULT_ENJU_MORPH_OPT="-m $ENJU_MORPH"
fi

# run enju
$BASE_DIR/bin/enju $DEFAULT_ENJU_TAGGER_OPT $DEFAULT_ENJU_MORPH_OPT "$@"

